#!/usr/bin/env bash
# Install Nginx, redirect and 404

sudo apt update -y
sudo apt install nginx -y

sudo sed -i "s/^\t\}$/\t\}\n\n\terror_page 404 \/404.html;/" /etc/nginx/sites-available/default
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null
